#!/bin/bash

if [[ $1 == "-v" ]]
then
    echo $(upd -v)
    exit
fi

if [ -z $1 ]
then
    echo "Error: To few arguments!"
else
    mount --bind /dev $1/dev
    mount --bind /dev/pts $1/dev/pts
    mount --bind /sys $1/sys
    mount --bind /proc $1/proc
    mount --bind /tmp $1/tmp

    chroot $1

    umount $1/dev
    umount $1/dev/pts
    umount $1/sys
    umount $1/proc
    umount $1/tmp
fi
