#!/bin/bash


if [[ $1 == "-v" ]]
then
    echo $(upd -v)
    exit
fi


mkdir -p /mounts
mkdir -p /mounts/-temp
mkdir -p /mounts/ubuntu
mkdir -p /mounts/debian
mkdir -p /mounts/1fleha
mkdir -p /mounts/2fleha
mkdir -p /mounts/cd
mkdir -p /mounts/fastfs
mkdir -p /mounts/ntfs
