#!/bin/bash

if [[ $1 == "-v" ]]
then
    version=$(apt-cache policy useful-package)
    version=$(python3 /usr/lib/useful-package/apt-cutter.py $version)
    echo $version
    exit
fi

if test -f /etc/apt/sources.list
then
    repo=$(cat /etc/apt/sources.list | grep deb | grep http | grep -v '#' | grep -m 1 -v 'deb-src')
    repo=$(echo -n $repo | cut -c 4-$(echo -n $repo | wc -c))
    repo=$(echo -n $repo | rev)
    repo=$(echo -n $repo | cut -c $(expr index "$repo" \/)-$(echo -n $repo | wc -c))
    repo=$(echo -n $repo | rev)
    reason=0
elif test -f /etc/apt/sources.list.d/official-package-repositories.list
then
    repo=$(cat /etc/apt/sources.list.d/official-package-repositories.list | grep deb | grep http | grep -v '#' | grep -m 3 -v 'deb-src')
    repo=$(echo -n $repo | cut -c 10-$(echo -n $repo | wc -c))
    repo=$(python3 ../lib/useful-package/repo.py $repo)
    repo=$(echo -n $repo | rev)
    repo=$(echo -n $repo | cut -c $(expr index "$repo" \/)-$(echo -n $repo | wc -c))
    repo=$(echo -n $repo | rev)
    reason=0
else
    repo='http://google.com'
    reason=1
fi

if
    if wget -q --spider $repo
    then
        apt update
        if [[ $1 == "-y" ]]
        then
            apt dist-upgrade -y
        else
            apt dist-upgrade
        fi
        apt autoremove --purge -y
        apt autoclean
        if which freshclam > /dev/null
            then freshclam
        fi
    else
        false
    fi
then
    echo "SYSTEM UPDATE IS DONE"
else
    if reason==0
    then
        if wget -q --spider 'http://google.com'
        then
            echo "Could not connect to sources of your system or find them"
        else
            echo "Check your internet connection!"
        fi
    else
        echo "Check your internet connection!"
    fi
fi
