#!/bin/bash

if [[ $1 == "-v" ]]
then
    echo $(upd -v)
    exit
fi

mkdir /mounts
mkdir /mounts/-temp
mkdir /mounts/ubuntu
mkdir /mounts/debian
mkdir /mounts/1fleha
mkdir /mounts/2fleha
mkdir /mounts/cd
mkdir /mounts/fastfs
mkdir /mounts/ntfs
