#!/bin/bash

repo=$(cat /etc/apt/sources.list | grep deb | grep http | grep -v '#' | grep -m 1 -v 'deb-src')
repo=$(echo -n $repo | cut -c 4-$(echo -n $repo | wc -c))
repo=$(echo -n $repo | rev)
repo=$(echo -n $repo | cut -c $(expr index "$repo" \/)-$(echo -n $repo | wc -c))
repo=$(echo -n $repo | rev)

if
    if wget -q --spider $repo
    then
        apt update
        if [[ $1 == "-y" ]]
        then
            apt dist-upgrade -y
        else
            apt dist-upgrade
        fi
        apt autoremove --purge -y
        apt autoclean
        if which freshclam > /dev/null
            then freshclam
        fi
    else
        false
    fi
then
    echo "SYSTEM UPDATE IS DONE"
else
    echo "Check your internet connection!"
fi
